### ISSUE TITLE
possible improvements

### ISSUE THREAD

**Issue by duck2** [midorikocak/pusula#1]
I have a couple of ideas for this:

- Choosing a light direction and casting a thicker shadow on the opposite side.
- Drag event for added images. Having to reset on any mistake would be frustrating.

Since voting is tomorrow, I am starting to implement those. Will send PR once done.

**Comment by midorikocak** [comment]
drag was a bit difficult and I did not want to use a library. light direction is a good idea, but needs a transparent layer I guess.

**Comment by duck2** [comment]
drag is not straightforward because of canvas transformations.

we would need to iterate over current images on a mouseDown event. but first the mouse coords should be translated to image space.

luckily we only apply translations and rotations with rotations strictly after translations. then translations can be stored as x,y coordinates and the final rotation as some angle. on a mouseDown event, we can rotate mousecoords the other way and subtract x,y to get image coordinates.

after that we would need to tie that image's x,y to mouse coords minus where it was grabbed and update on certain intervals.

however that seems to require some refactor and will possibly result in a sizable patch.

**Comment by midorikocak** [comment]
can you resolve conflicts?
